apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
        - name: client
          image: docker.io/zhzhxtrrk/fn:client
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: server.target
              value: server.default.svc.cluster.local
